### ISSUE TITLE
Pressing the start brewing button when a process is in progress should take you to the process screen

### ISSUE THREAD

**Issue by drmwve** [drmwve/Capstone-Project#14]
Backing up a little bit, I think it should just be very clear from the main menu when a process is in progress and easy for the user to get to the process status screen. Either that, or it should be impossible for the user to go back to the main menu from the process status screen without stopping the process, and there should instead be a button to take you to the Device Status but the main menu button is replaced with a button that takes you back to the process status screen. 

I'm leaning more towards the second option, since that would prevent a whole range of possible unintended user interactions, since after all, you shouldn't really be able to do anything but monitor the process and device status when a process is running until you kill it. However, MainMenu/ProcessStatus button on the device status screen would have to be changed based on which menu the user got to that screen from, which would take a little thinking. 

What do you think?

**Comment by TCTaco** [comment]
I believe the second option would be easier to implement, originally I was planning on implementing the first option but my attempts on it either didn't work or like you said, did some unintended things.

I think I could use the process complete and started signals to swap out the "Return to main menu" button on the device status screen and change it to "Return to Process Status". And replacing the main menu button on process status is very simple.

I will take a look at implementing this today.

**Comment by TCTaco** [comment]
bc34e40f1e12f6225da6e61c0962d9ff499e3fd7, 161ca40136aa813fc2e41549cd79d010db3e2830, 5860a364e90c57813aae28dd88f32f98ea73a119, cbd40f55444ac432b7cecf775fa57574ff894744, and 03654c4e2fb1e1dc5bf614c082b98c96636526aa all address this and it appears to be functioning.
