### ISSUE TITLE
It should be obvious when a Quick Brew has unsaved changes

### ISSUE THREAD

**Issue by drmwve** [drmwve/Capstone-Project#17]
This should be pretty simple. The save button could be disabled by default, and disabled when you change selected recipes or save the current recipe. Pressing any button that changes the recipe should re-enable the button. When the user presses the start brew button, or attempts to change the selected recipe, the UI should pop up a dialog box asking if they'd like to save their unsaved changes first. 

Importantly, this function would have to be connected to the combo box change signal _before_ the changeSelectedRecipe function so the UI elements don't change over first. I don't think the dialog box would block execution either, so this function would have to copy the recipe from the UI to a local variable, pop the yes/no dialog box, and if the user saves, put the recipe in the savedBrewRecipes variable and call the pickler save function itself instead of just calling the existing saveRecipe function in the Brew Config class. 

Alternatively, going back to #7 , we could save any change as soon as it's made. This would be as simple as connecting the saveRecipe function to all of the buttons that change a recipe. Then there wouldn't even need to be a save recipe button. I feel like this is unclear and could be inflexible if a user wants to significantly change a recipe once without saving it.

**Comment by TCTaco** [comment]
https://github.com/drmwve/Capstone-Project/commit/55496fd2307c1031456b27848a031d88a53dd40a implements this.

The save button is disabled by default. Pressing any of the buttons that would change a recipe re-enable the button. Pressing the save button will cause it to disable itself again until another change is made. If the user attempts to start a brew before saving, they are presented with a question box that calls to save the recipe if they press yes. If they press no, the box closes and the brew starts.
