### ISSUE TITLE
There should be limitations on the mash temperature

### ISSUE THREAD

**Issue by drmwve** [drmwve/Capstone-Project#18]
A typical mash is between 146 and 156 degrees F. If the user attempts to go out of this range, a dialog should pop up informing them that this is beyond the ideal temperature. There should be a flag to ensure this only happens once, which is reset when they go back into the acceptable range. These numbers should be added as constants along with the other ones at the top of the Brew Config class. 

There's already code to prevent the user from going below or above the absolute maximum range, which I've now set to 130-168 after some research. Reaching the limits of this range should disable the relevant mash temperature button.

**Comment by TCTaco** [comment]
Honestly we should probably just set the lower limit to 146, from my understanding mashing below even 150 requires a longer mash time which we don't give the user control over. If you really want a wider range of acceptable temperatures then we would need to look into allowing the user to select a longer mash with the lower temperature.

I'm not sure if it's worth adding that feature at this point as it's just more work that isn't 100% necessary and I know we're all busy this quarter.

**Comment by drmwve** [comment]
> Honestly we should probably just set the lower limit to 146, from my understanding mashing below even 150 requires a longer mash time which we don't give the user control over. If you really want a wider range of acceptable temperatures then we would need to look into allowing the user to select a longer mash with the lower temperature.
> 
> I'm not sure if it's worth adding that feature at this point as it's just more work that isn't 100% necessary and I know we're all busy this quarter.

That's fine, you can change it and yeah just get the disabling the buttons when you reach the min/max temps added.

**Comment by TCTaco** [comment]
After working on it some, I found the pop up window to be rather annoying. I think that we should reserve pop up windows for when we need to relay important information to the user that isn't readily apparent. In lieu of this, the buttons simply disable when the min or max temperature is reached.

The buttons disabling should convey that the limits have been reached, and if this isn't obvious to the user it can be referenced in the user manual.

https://github.com/drmwve/Capstone-Project/commit/55496fd2307c1031456b27848a031d88a53dd40a is the commit that addresses this.
