### ISSUE TITLE
Aborting a brew does not reset progress screen

### ISSUE THREAD

**Issue by drmwve** [drmwve/Capstone-Project#2]
When you abort a brew on the brew progress screen and try to start another brew, it still says "aborting brew" and the pause and abort buttons are grayed out.

**Comment by TCTaco** [comment]
This is remidied on the cleaning screen by assuming the system runs on timers, I can easily transplant the timers to work in a similar fashion on the brew progress if they're nessecary.

**Comment by drmwve** [comment]
> This is remidied on the cleaning screen by assuming the system runs on timers, I can easily transplant the timers to work in a similar fashion on the brew progress if they're nessecary.

Take a look at #5, you should now be able to define a slot which resets the screen, which is called when pressing the abort button or when the execution code emits the (yet to be implemented) process complete signal.

**Comment by TCTaco** [comment]
Should be working as of https://github.com/drmwve/Capstone-Project/commit/a9cc87e519c9b7d485ca3d0119835a6f394dbac2
