### ISSUE TITLE
DeviceStatusControls needs to be updated

### ISSUE THREAD

**Issue by drmwve** [drmwve/Capstone-Project#20]
1. Updating the screen needs to catch the hardware state signal emitted every quarter second from the Device Handler (connect them in the autobrewer file) and update the UI elements using the supplied Hardware State variable instead of defining its own internal state variables for everything.
2. All functions which call component control functions must catch any ComponentControlError with a try-catch and display a popup notifying the user why their action was unsuccessful if it generates an error. When you catch the error, there should be a way to read the message it sends and I used pretty descriptive messages which can be output directly to the popup.
3. We're now using PID loops to control the temperatures. This is mostly for the HLT and MT, but works for all 3 (boiling liquid can't use a PID since boiling water always has a temperature of 212, but it's possible to set any temp on the BK at the moment). We should think about how to allow the user to get and set the target temperatures and see if the PID is currently controlling a kettle. 

1 and 2 are definitely the priority, we can get to this part later, but 3 related to the other two so I'm putting it in this issue.

**Comment by TCTaco** [comment]
I'm not sure what you mean with 1, there's no internal state variables. If you're referring to the 'state' arrays, those are the arrays that point to a text label, not a variable. The actual state update is done through the device handler in the updateState function. You're gonna need to get more specific or clarify what you mean here.

2 I can probably figure out but any examples of how to code errors would be helpful as I've never messed with it.

**Comment by drmwve** [comment]
> I'm not sure what you mean with 1, there's no internal state variables. If you're referring to the 'state' arrays, those are the arrays that point to a text label, not a variable. The actual state update is done through the device handler in the updateState function. You're gonna need to get more specific or clarify what you mean here.
> 
> 2 I can probably figure out but any examples of how to code errors would be helpful as I've never messed with it.

Yeah, I misunderstood that. Looking closer at it now, it seems like there's two issues:

1. The component control functions you've defined don't actually call the functions on the device handler yet. When you're implementing this, it'll probably simplify things for you to combine the two way and three way functions since they're defined in the same array on the hardware side. The global variable for the handler is defined in the DeviceHandler file as 'devicehandler' and if you branch off development you'll get what should be the finalized API for all the device handler functions you'll need to call.
 
2. Updating the state of the UI happens in the control functions you've defined, which means the UI only gets updated when the UI tries to change something and it assumes an attempt to change something was successful. All the label updating code should be in a function that's connected to the hardware state signal emitted by the device handler, which reads that signal's data to set the labels and whatnot. The intended model is the UI requests changes from the hardware, and displays the current hardware state as transmitted by the hardware in the stateSignal signal.

I feel like we've talked about this before so I apologize if I'm repeating myself. As far as the try-catch thing, on looking into it, it's actually called try-except and here's a good primer, including a bit about how to save the exception as a variable and print its message:
https://www.learnbyexample.org/python-exceptions-try-except/

The gist of it is a function can define Exceptions which reflect some kind of error state, invalid input, whatever you want, really. This allows the calling code to catch those Exceptions and do error-handling for particular invalid states. I created a ComponentControlError which is used in certain parts of the Device Handler (I think just the pumps, servo, and heating elements, but check for "raise" statements any time you use a function from it) to give you an easy way to detect when the user attempts to manually do something they shouldn't be allowed to do, and inform them. Text me if you're still confused after reading this and the link I shared.

**Comment by TCTaco** [comment]
I'm confused how the functions aren't actually calling the device handlers functions, I figured since I got the log message from the function on the device handlers side it was connected and getting the request?

My original intention was to just update the hardware states regularly with a looping timer, but only while the user was on the page. I assumed the error handling would mostly come from the device handlers side and that I just needed to keep the ui updated. Regardless, the way the logic executes if the ui did get out of sync with actual states it would self correct when a button was pushed and, in the case of ball valves you would get a request to open a valve that's already open, turn off a heater that's already off etc.

Probably give me a call tomorrow when you get home from work and we can talk about it. I don't mind redoing this page but it's not going to be done in a timely manner, I need time redirected to DME (which is not going amazing) and to job hunting. My goal is to work on this primarily for a few hours on the weekends.

**Comment by TCTaco** [comment]
This is done with the exception of the pop up error messages, which I will be working on sometime this week.

**Comment by TCTaco** [comment]
https://github.com/drmwve/Capstone-Project/commit/4f6a6d96465aa733f01c820fd1000d6ad64e2c82 has errors for one of the pages, I'm not sure how to grab your specific error messages that are put out to the terminal is the only real roadblock with this.

**Comment by drmwve** [comment]
> [4f6a6d9](https://github.com/drmwve/Capstone-Project/commit/4f6a6d96465aa733f01c820fd1000d6ad64e2c82) has errors for one of the pages, I'm not sure how to grab your specific error messages that are put out to the terminal is the only real roadblock with this.

I pushed a commit that shows how to change it. You just save the error as a variable in the except statement and use the variable directly, which contains the error message.

**Comment by TCTaco** [comment]
Ok thanks that's pretty straight forward. I'll copy this across screens and work on the other issues tomorrow.

**Comment by TCTaco** [comment]
Pop up error messages are in place with https://github.com/drmwve/Capstone-Project/commit/9493330c92b8f427ac1909d69c217eeecfd7e32b
