### ISSUE TITLE
Hop dispenser labels show up even when you decrease the number of hop cartridges

### ISSUE THREAD

**Issue by drmwve** [drmwve/Capstone-Project#3]
The intended function is that decreasing the number of hop cartridges doesn't cause the buttons along the bottom of the screen to move, keeping the hop dispenser labels in place is currently a workaround to prevent that from happening. Now that the Brew Config screen has been reworked as a widget and we can dig into it with Designer, let's try to get it working as intended when we have time.

**Comment by TCTaco** [comment]
This is fixed with commit https://github.com/drmwve/Capstone-Project/commit/d3b046cb6cfbabd0a5f2c2b79c44793c8c5acb1d
