### ISSUE TITLE
Styler branch

### ISSUE THREAD

**Issue by TCTaco** [drmwve/Capstone-Project#6]
I created a new branch called styler which has my implementation on styling the GUI windows and widgets, it adds styler.py to the GUI folder which handles all the palette color assignments. Please review commit: https://github.com/drmwve/Capstone-Project/commit/b6772ef9cb15da5e57f0b2d0270ae3af8ccd95ec and if the code, style, and feature look good the branch can me merged back to development and deleted.

**Comment by drmwve** [comment]
I like it. Seems like it'd be pretty easy to change the style if we wanted to in the future as well, but this is much better than the default.

**Comment by drmwve** [comment]
Having tested this on the touchscreen, it's too dark. I think a light background with large, dark text is better for readability.

**Comment by TCTaco** [comment]
Does the touchscreen not have brightness/contrast settings? If not we can just add about 50 or so to the RGB values and that will probably do the trick.

**Comment by drmwve** [comment]
> Does the touchscreen not have brightness/contrast settings? If not we can just add about 50 or so to the RGB values and that will probably do the trick.

No, it's a cheap touchscreen with a mediocre backlight and a bad viewing angle. Light text on dark backgrounds just don't look very good, but if you want to try that and push it to development I'll see how it looks on the screen tonight.

**Comment by drmwve** [comment]
@TCTaco, I tried it with the new color settings. I still think going back to a light background with dark text is the way to go, this screen's color qualities just aren't great.
